
                                                                                                                                                                                                                                                                                  const appContainerStyle = {
                                                                                                                                                                                                                                                                                        display: 'flex',
                                                                                                                                                                                                                                                                                              flexWrap: 'wrap',
                                                                                                                                                                                                                                                                                                    justifyContent: 'center',
                                                                                                                                                                                                                                                                                                          alignItems: 'flex-start',
                                                                                                                                                                                                                                                                                                                backgroundColor: '#f4f7f6',
                                                                                                                                                                                                                                                                                                                      minHeight: '100vh'
                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                              <div style={appContainerStyle}>
                                                                                                                                                                                                                                                                                                                                    {people.map(person => (
                                                                                                                                                                                                                                                                                                                                                  <GreetingCard
                                                                                                                                                                                                                                                                                                                                                                    key={person.id}
                                                                                                                                                                                                                                                                                                                                                                                      name={person.name}
                                                                                                                                                                                                                                                                                                                                                                                                        age={person.age}
                                                                                                                                                                                                                                                                                                                                                                                                                          greeting={person.greeting}
                                                                                                                                                                                                                                                                                                                                                                                                                                            favoriteColor={person.favoriteColor}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;