                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                <h2>Work Experience</h2>
                                                                                                                                                                                                                                            <p>Content for the experience tab goes here.</p>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                      {/* Show this content only if currentActiveTab is 2 */}
                                                                                                                                                                                                                                                                              {currentActiveTab === 2 && (
                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                    <h2>Review & Submit</h2>
                                                                                                                                                                                                                                                                                                                <p>Content for the review tab goes here.</p>
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                              <div className="tab-navigation">
                                                                                                                                                                                                                                                                                                                                                      <button>Previous</button>
                                                                                                                                                                                                                                                                                                                                                              <button>Next</button>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                          export default Tabs;