                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" disabled={status === 'loading'}>
                                                                                                                                                                                                                                                                                                                                                                                                                          {status === 'loading' ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="spinner"></span> Sending...
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Subscribe'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {status === 'error' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="error-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>⚠️ {error || 'Submission error'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={resetForm}>Try Again</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default NewsletterForm;
